RentaPropiedades/Propiedades/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

urlpatterns = [
    path('arrendador_bienvenido/',
         views.arrendador_bienvenido, name='arrendador_bienvenido'),
    path('agregar/',
         views.nueva_propiedad, name='agregar_propiedad'),
    path('lista_propiedades/',
         views.listaPropiedades, name='lista_propiedades'),
    path('detalle_propiedad/<int:id>',
         views.detalle_propiedad, name='detalle_propiedad'),
    path('detalles_arrendador/<int:id>',
         views.detalles_arrendador, name='detalles_arrendador'),
    path('obtener_colonias/',
         views.obtener_colonias, name='obtener_colonias'),
    path('propiedades_arrendador/',
         views.propiedades_arrendador, name='propiedades_arrendador'),
    path('editar_propiedad/<int:id>',
         views.editarPropiedad, name='editar_propiedad'),
    path('eliminar/<int:id>/',
         views.eliminarPropiedad, name='eliminar_propiedad'),
    path('confirmacion_eliminacion_propiedad/<int:id>',
         views.confirmarEliminacionPropiedad,
         name='confirmacion_eliminacion_propiedad'),
    path('favoritos/',
         views.lista_favoritos, name='lista_favoritos'),
    path('favoritos/agregar/<int:propiedad_id>/',
         views.agregaraListaFavoritos, name='agregaraListaFavoritos'),
    path('favoritos/eliminar/<int:propiedad_id>',
         views.eliminarDeListaFavorito, name='eliminarDeListaFavoritos'),
    path('confirmar_eliminacion_favorito/<int:propiedad_id>',
         views.confirmarEliminacionFavorito,
         name='confirmar_eliminacion_favorito'),
    path('filtrar/',
         views.filtrarPropiedades, name='filtrar_propiedades'),
    path('resenas/<int:id>',
         views.ver_resenas, name='lista_resenas'),
    path('agregar_resena/<int:id>',
         views.CrearResena, name='agregar_resena'),
    path('editar_resena/',
         views.EditarResena, name='editar_resena'),
    path('eliminar_resena/',
         views.EliminarResena, name='eliminar_resena'),
    path('confirmacion_eliminacion_resena/',
         views.ConfirmacionEliminacionResena,
         name='confirmacion_eliminacion_resena'),
    path('interesados/<int:id>',
         views.lista_interesados, name='lista_interesados'),
    path('indicar_interes/<int:id>',
         views.indicarInteres, name='indicar_interes'),
    path('detalles_estudiante/<int:id>',
         views.detalles_estudiante, name='detalles_estudiante'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

RentaPropiedades/RentaPropiedades/urls.py
from django.contrib import admin
from Propiedades.views import Bienvenida
from perfiles.views import CustomLoginView
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Propiedades/', include('Propiedades.urls')),
    path('', CustomLoginView.as_view(), name="login"),
    path('home/', Bienvenida.as_view(), name="bienvenida"),
    path('perfiles/', include('perfiles.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

RentaPropiedades/perfiles/urls.py
from django.contrib.auth.views import LogoutView
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

urlpatterns = [
    path('logout/', LogoutView.as_view(),
         name='logout'),
    path('nuevo_estudiante/',
         views.RegistrarEstudiante,
         name='nuevo_estudiante'),
    path('nuevo_arrendador/',
         views.RegistrarArrendador,
         name='nuevo_arrendador'),
    path('compromiso/',
         views.compromiso,
         name='compromiso'),
    path('registrar_contrasena/',
         views.registrar_contrasena,
         name='contrasena'),
    path('confirmacion_cuenta/',
         views.confirmar_cuenta,
         name='confirmar'),
    path('perfil_estudiante/',
         views.verPerfilEstudiante,
         name='perfil_estudiante'),
    path('perfil_arrendador/',
         views.verPerfilArrendador,
         name='perfil_arrendador'),
    path('editar_perfil_estudiante/',
         views.editar_perfil_estudiante,
         name='editar_perfil_estudiante'),
    path('editar_perfil_arrendador/',
         views.editar_perfil_arrendador,
         name='editar_perfil_arrendador'),
    path('eliminar_estudiante/',
         views.eliminarEstudiante,
         name='eliminar_estudiante'),
    path('eliminar_arrendador/',
         views.eliminarArrendador,
         name='eliminar_arrendador'),
    path('confirmar_eliminacion_arrendador/',
         views.confirmaEliminacionArrendador,
         name='confirmar_eliminacion_arrendador'),
    path('confirmar_eliminacion_estudiante/',
         views.confirmaEliminacionEstudiante,
         name='confirmar_eliminacion_estudiante'),
]

if settings.DEBUG:  # pragma no cover
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

RentaPropiedades/Propiedades/models.py
from django.db import models


class Propiedad(models.Model):
    id = models.AutoField(primary_key=True)
    descripcion = models.CharField(max_length=200)
    precio = models.IntegerField()
    tipo = models.IntegerField(
        choices=[(1, 'Casa'),
                 (2, 'Departamento'),
                 (3, 'Cuarto')])
    ubicacion = models.CharField(max_length=100)
    serviciosIncluidos = models.BooleanField(default=False)
    arrendador = models.ForeignKey(
        "perfiles.Arrendador", verbose_name="Arrendador",
        on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.ubicacion} - {self.precio}"  # pragma: no cover


class ImagenPropiedad(models.Model):
    propiedad = models.ForeignKey(
        "Propiedades.Propiedad",
        verbose_name="Propiedad",
        on_delete=models.CASCADE)
    imagen = models.ImageField(
        'imagen',
        upload_to='imagenes',
        null=True,
        blank=True)


class Municipio(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=20)

    def __str__(self):
        return self.nombre


class Colonia(models.Model):
    municipio = models.ForeignKey(
        "Propiedades.Municipio",
        verbose_name="Municipio",
        on_delete=models.CASCADE)
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre  # pragma: no cover


class Favorito (models.Model):
    id = models.AutoField(primary_key=True)
    estudiante = models.ForeignKey("perfiles.Estudiante",
                                   verbose_name="Estudiante",
                                   on_delete=models.CASCADE,
                                   related_name='favoritos_estudiante')
    propiedad = models.ForeignKey("Propiedades.Propiedad",
                                  verbose_name="Propiedad",
                                  on_delete=models.CASCADE,
                                  related_name='favoritos_propiedad')


class Resena(models.Model):
    resena_id = models.AutoField(primary_key=True)
    estudiante = models.ForeignKey("perfiles.Estudiante",
                                   verbose_name="Estudiante",
                                   on_delete=models.CASCADE,
                                   related_name='resenas_estudiante')
    propiedad = models.ForeignKey("Propiedades.Propiedad",
                                  verbose_name="Propiedad",
                                  on_delete=models.CASCADE,
                                  related_name='resenas_propiedad')
    descripcion = models.TextField(max_length=500)
    calificacion = models.IntegerField(default=0)
    fecha = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"{self.estudiante} - {self.fecha}"  # pragma: no cover


class Estudiante_Interesado(models.Model):
    estudiante = models.ForeignKey("perfiles.Estudiante",
                                   verbose_name="Estudiante",
                                   on_delete=models.CASCADE,
                                   related_name='interesado_estudiante')
    propiedad = models.ForeignKey("Propiedades.Propiedad",
                                  verbose_name="Propiedad",
                                  on_delete=models.CASCADE,
                                  related_name='interesado_propiedad')

RentaPropiedades/perfiles/models.py
from django.db import models
from django.contrib.auth.models import User


class Estudiante (models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=30)
    apellidos = models.CharField(max_length=50)
    edad = models.IntegerField()
    sexo = models.CharField(max_length=1, choices=[(
        'M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')])
    foto_perfil = models.ImageField(
        'Foto', upload_to='perfiles', null=True, blank=True)
    universidad_actual = models.CharField(max_length=100)
    telefono = models.CharField(max_length=10)
    whatsapp = models.CharField(max_length=10)
    correo = models.CharField(max_length=100)
    preferencias_busqueda = models.CharField(max_length=500)
    pasatiempos = models.CharField(max_length=500)
    usuario = models.OneToOneField(
        User, verbose_name="Usuario", on_delete=models.CASCADE)


class Arrendador (models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=30)
    apellidos = models.CharField(max_length=50)
    edad = models.IntegerField()
    sexo = models.CharField(max_length=1, choices=[(
        'M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')])
    foto_perfil = models.ImageField(
        'perfil', upload_to='perfiles', null=True, blank=True)
    ocupacion = models.CharField(max_length=100)
    telefono = models.CharField(max_length=10)
    whatsapp = models.CharField(max_length=10)
    correo = models.CharField(max_length=100)
    preferencias_arrendatarios = models.CharField(max_length=500)
    usuario = models.OneToOneField(
        User, verbose_name="Usuario", on_delete=models.CASCADE)

RentaPropiedades/Propiedades/forms.py
from django import forms
from Propiedades.models import Propiedad, ImagenPropiedad, Resena


class FormPropiedad(forms.ModelForm):

    class Meta:
        model = Propiedad
        exclude = ['ubicacion', 'arrendador']
        widgets = {
            'descripcion': forms.TextInput(
                attrs={'class': 'form-control',
                       'placeholder': 'Ingresa la descripción de la propiedad'}
            ),
            'precio': forms.NumberInput(
                attrs={'class': 'form-control',
                       'placeholder': 'Precio de la propiedad',
                       'min': 100, 'title': 'Solo precios superiores a $100'}
            ),
            'tipo': forms.Select(
                attrs={'class': 'form-control'}
            ),
        }

    def clean_precio(self):
        precio = self.cleaned_data.get('precio')
        if precio < 100:
            raise forms.ValidationError(
                'El precio debe ser mayor o igual a 100.')
        return precio


class FormImagenPropiedad(forms.ModelForm):

    class Meta:
        model = ImagenPropiedad
        fields = ['imagen']


class FiltrosPropiedad(forms.Form):
    tipo = forms.ChoiceField(
        choices=[(1, 'Casa'), (2, 'Departamento'), (3, 'Cuarto')],
        required=False
    )
    servicios = forms.BooleanField(
        required=False,
        initial=True
    )
    precio_min = forms.IntegerField(
        required=False,
        min_value=100,
        widget=forms.NumberInput(attrs={'size': '10'})
    )
    precio_max = forms.IntegerField(
        required=False,
        min_value=100,
        widget=forms.NumberInput(attrs={'size': '10'})
    )


class CalificacionEstrellasFormField(forms.TypedChoiceField):

    def __init__(self, *args, **kwargs):
        kwargs['choices'] = [(i, i) for i in range(1, 6)]
        kwargs['coerce'] = int
        super().__init__(*args, **kwargs)


class FormResena(forms.ModelForm):
    calificacion = CalificacionEstrellasFormField()

    class Meta:
        model = Resena
        fields = ['descripcion', 'calificacion']

RentaPropiedades/Propiedades/templates/crear_resena.html
{% extends 'base.html' %}

{% block nav-Lista_de_propiedades %}
    active
{% endblock nav-Lista_de_propiedades %}

{% block estilos %}
    <style>
        .contenedor_estrellas i {
            color: #f9d71c;
        }

        #id_descripcion {
            width: 50%; /* Establece el ancho deseado */
            height: 150px; /* Establece la altura deseada */
            resize: vertical; /* Permite redimensionar verticalmente */
        }

        @media (max-width: 767px) {
            /* Estilos específicos para dispositivos con ancho de pantalla de 767px o menos (celulares) */
            #id_descripcion {
                width: 100%; /* Establece el ancho deseado */
                height: 150px; /* Establece la altura deseada */
                resize: vertical; /* Permite redimensionar verticalmente */
            }
        }

        .error-message {
            color: red;
            display: none; /* Oculto por defecto */
        }
    </style>
{% endblock estilos %}
    
{% block contenido %}
<h1>Agregar Reseña</h1><br>
    <form method="post" id="resena-form">
        {% csrf_token %}
        <strong>{{ form.descripcion.label_tag }}</strong>
        {{ form.descripcion }}
        <br>
        <strong>{{ form.calificacion.label_tag }}</strong>
        <div class="contenedor_estrellas" id="contenedor-estrellas">
            {% for i in rango_estrellas %}
                <span class="estrella" data-valor="{{ i }}">
                    {% if i <= resena.calificacion %}
                        <i class="fas fa-star" style="font-size: 2em;"></i>
                    {% else %}
                        <i class="far fa-star" style="font-size: 2em;"></i>
                    {% endif %}
                </span>
            {% endfor %}
            <!-- Campo oculto para la calificación -->
            <select name="calificacion" id="id_calificacion" style="display: none;">
                <option value="">-</option>
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
            </select>
        </div>
        <br>
        <span class="error-message" id="calificacion-error">Por favor, selecciona una calificación.</span>
        <br>
        <span>
            <a href="{% url 'lista_resenas' propiedad_id %}" class="btn btn-warning">Cancelar</a>
            <button class="btn btn-info" type="submit">Guardar</button>
        </span>
    </form>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        const estrellas = document.querySelectorAll('.estrella');
        const inputCalificacion = document.getElementById('id_calificacion');
        const form = document.getElementById('resena-form');
        const errorMessage = document.getElementById('calificacion-error');

        estrellas.forEach(function (estrella) {
            estrella.addEventListener('click', function () {
                const valorEstrella = estrella.dataset.valor;

                // Actualizar el campo oculto con la nueva calificación
                inputCalificacion.value = valorEstrella;

                // Resaltar las estrellas seleccionadas
                estrellas.forEach(function (e, index) {
                    if (index < valorEstrella) {
                        e.innerHTML = '<i class="fas fa-star" style="font-size: 2em;"></i>';
                    } else {
                        e.innerHTML = '<i class="far fa-star" style="font-size: 2em;"></i>';
                    }
                });

                // Ocultar el mensaje de error
                errorMessage.style.display = 'none';
            });
        });

        form.addEventListener('submit', function (event) {
            if (inputCalificacion.value === "") {
                event.preventDefault(); // Evita que el formulario se envíe
                errorMessage.style.display = 'block'; // Muestra el mensaje de error
            }
        });
    });
</script>
{% endblock contenido %}

RentaPropiedades/Propiedades/templates/detalles_arrendador.html
{% extends 'base.html' %}
{% load static %}


{% block nav-Lista_de_propiedades %}
active
{% endblock nav-Lista_de_propiedades %}

{% block contenido %}
<div class="formulario-container">

    <div class="card card-user">
      <div class="card-image">
          <img src="https://ununsplash.imgix.net/photo-1431578500526-4d9613015464?fit=crop&fm=jpg&h=300&q=75&w=400" alt="...">
      </div>
      <div class="card-body">
        <div class="author">
          <a>
            <img class="avatar border-gray" src="{{ arrendador.foto_perfil.url }}" alt="...">
            <h5 class="title" style="color: purple;">{{ arrendador.nombre }} {{ arrendador.apellidos }}</h5>
          </a>
          <p class="description"><strong>Arrendador</strong></p>
          <p class="description"><strong>Edad: </strong>{{ arrendador.edad }}</p>
          <p class="description"><strong>Sexo: </strong>{{ arrendador.get_sexo_display }}</p>
          <p class="description"><strong>Ocupación: </strong>{{ arrendador.ocupacion }}</p>
          <p class="description"><strong>Teléfono: </strong>{{ arrendador.telefono }}</p>
          <p class="description"><strong>Preferencias de perfil de arrendatario: </strong>{{ arrendador.preferencias_arrendatarios }}</p>
        </div>
    </div>
    <hr>
    <div class="button-container mr-auto ml-auto">
        <div class="button-container mr-auto ml-auto">
          <button class="btn btn-simple btn-link btn-icon">
            <a href="tel: {{arrendador.telefono}}"><i class="fa fa-phone" style="width: 35px; font-size: 35px;"></i></a>
          </button>
          <button class="btn btn-simple btn-link btn-icon">
            <a href="https://api.whatsapp.com/send?phone=52{{ arrendador.whatsapp }}"><i class="fab fa-whatsapp"></i></a>
          </button>
          <button class="btn btn-simple btn-link btn-icon">
            <a href="mailto: {{arrendador.correo}}"><i class="fa fa-envelope"></i></a>
          </button>
        </div>
    </div>
</div>
</div>


{% endblock contenido %}

RentaPropiedades/Propiedades/templates/detalles_estudiante.html
{% extends 'base.html' %}
{% load static %}

{% block contenido %}
<div class="formulario-container">

    <div class="card card-user">
      <div class="card-image">
          <img src="https://ununsplash.imgix.net/photo-1431578500526-4d9613015464?fit=crop&fm=jpg&h=300&q=75&w=400" alt="...">
      </div>
      <div class="card-body">
        <div class="author">
          <a>
            <img class="avatar border-gray" src="{{ estudiante.foto_perfil.url }}" alt="...">
            <h5 class="title" style="color: purple;">{{ estudiante.nombre }} {{ estudiante.apellidos }}</h5>
          </a>
          <p class="description"><strong>Estudiante</strong></p>
          <p class="description"><strong>Edad: </strong>{{ estudiante.edad }}</p>
          <p class="description"><strong>Sexo: </strong>{{ estudiante.get_sexo_display }}</p>
          <p class="description"><strong>Universidad: </strong>{{ estudiante.universidad_actual }}</p>
          <p class="description"><strong>Pasatiempos: </strong>{{ estudiante.pasatiempos }}</p>
          <p class="description"><strong>Teléfono: </strong>{{ estudiante.telefono }}</p>
          <p class="description"><strong>Preferencias de búsqueda: </strong>{{ estudiante.preferencias_busqueda }}</p>
        </div>
    </div>
    <hr>
    <div class="button-container mr-auto ml-auto">
        <div class="button-container mr-auto ml-auto">
          <button class="btn btn-simple btn-link btn-icon">
            <a href="tel: {{estudiante.telefono}}"><i class="fa fa-phone" style="width: 35px; font-size: 35px;"></i></a>
          </button>
          <button class="btn btn-simple btn-link btn-icon">
            <a href="https://api.whatsapp.com/send?phone=52{{ estudiante.whatsapp }}"><i class="fab fa-whatsapp"></i></a>
          </button>
          <button class="btn btn-simple btn-link btn-icon">
            <a href="mailto: {{estudiante.correo}}"><i class="fa fa-envelope"></i></a>
          </button>
        </div>
    </div>
</div>
</div>


{% endblock contenido %}

RentaPropiedades/Propiedades/templates/editar_propiedad.html
{% extends 'base.html' %}
{% load static %}


{% block nav-Mis_propiedades %}
active
{% endblock nav-Mis_propiedades %}


{% block contenido %}


{% if messages %}
{% for message in messages %}
    {% if message.tags == 'success' %}
        <div class="alert alert-success" role="alert">
        {{ message }}
        </div>
    {% elif message.tags == 'warning' %}
        <div class="alert alert-danger" role="alert">
        {{ message }}
        </div>
    {% else %}
        <div class="alert" role="alert">
        {{ message }}
        </div>
    {% endif %}
{% endfor %}
{% endif %}

<div class="text-center">
    <h1>Editar Propiedad</h1>
</div>
<div class="row justify-content-center">
    <div class="col-lg-6 col-md-8">
        <div class="card shadow-lg p-3 mb-5 bg-white rounded">
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        {{ form.descripcion.label_tag }}
                        {{ form.descripcion }}
                    </div>
                    <div class="form-group">
                        {{ form.precio.label_tag }}
                        {{ form.precio }}
                    </div>
                    <div class="form-group">
                        {{ form.tipo.label_tag }}
                        {{ form.tipo }}
                    </div>
                    
                    <div class="form-group">
                        {{ form.serviciosIncluidos.label_tag }}
                        {{ form.serviciosIncluidos }}
                    </div> 
                
                    <div class="form-group">
                        <label for="id_imagen">Nueva Imagen</label>
                        <input type="file" name="imagen" id="id_imagen" accept="image/*">
                    </div>
                
                    {% for imagen in imagenes_propiedad %}
                    <div class="form-group">
                        <label for="id_imagen_{{ forloop.counter }}">Imagen {{ forloop.counter }}</label>
                        {% if imagen.imagen %}
                        <br>
                        <img src="{{ imagen.imagen.url }}" alt="Imagen actual" style="max-width: 200px; max-height: 200px">
                        <input type="checkbox" name="eliminar_imagen_{{ imagen.id }}" id="eliminar_imagen_{{ imagen.id }}">
                        <label for="eliminar_imagen_{{ imagen.id }}">🗑️ Eliminar</label>
                        {% endif %}
                    </div>
                    {% endfor %}
                
                    <div class="d-flex justify-content-between align-items-center">
                        <a class="btn btn-danger" href="{% url 'propiedades_arrendador' %}" role="button">Cancelar</a>
                        <button type="submit" class="btn btn-success"  id="btn-guardar">Guardar cambios</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock contenido %}
    

RentaPropiedades/Propiedades/templates/editar_resena.html
{% extends 'base.html' %}

{% block nav-Lista_de_propiedades %}
    active
{% endblock nav-Lista_de_propiedades %}

{% block estilos %}
    <style>

        .contenedor_estrellas i {
            color: #f9d71c;
        }

        #id_descripcion {
            width: 50%; /* Establece el ancho deseado */
            height: 150px; /* Establece la altura deseada */
            resize: vertical; /* Permite redimensionar verticalmente */
        }

        @media (max-width: 767px) {
            /* Estilos específicos para dispositivos con ancho de pantalla de 767px o menos (celulares) */
            #id_descripcion {
                width: 100%; /* Establece el ancho deseado */
                height: 150px; /* Establece la altura deseada */
                resize: vertical; /* Permite redimensionar verticalmente */
            }
        }
    </style>
{% endblock estilos %}

{% block contenido %}
    <h1>Editar Reseña</h1><br>
    <form method="post">
        {% csrf_token %}
        <strong>{{form.descripcion.label_tag}}</strong>
        {{ form.descripcion }}
        <br>
        <strong>{{form.calificacion.label_tag}}</strong>
        <div class="contenedor_estrellas" id="contenedor-estrellas">
            {% for i in rango_estrellas %}
                <span class="estrella" data-valor="{{ i }}">
                    {% if i <= resena.calificacion %}
                        <i class="fas fa-star" style="font-size: 2em;"></i>
                    {% else %}
                        <i class="far fa-star" style="font-size: 2em;"></i>
                    {% endif %}
                </span>
            {% endfor %}
            <!-- Campo oculto para la calificación -->
            {{ form.calificacion }}
        </div>
        <br>
        <span>
            <a href="{% url 'lista_resenas' propiedad_id %}" class="btn btn-warning">Cancelar</a>
            <button class="btn btn-info" type="submit">Guardar</button>
        </span>
    </form>

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const estrellas = document.querySelectorAll('.estrella');
            const inputCalificacion = document.getElementById('id_calificacion');
            const calificacionActual = parseInt(inputCalificacion.value);  // Obtener la calificación actual

            // Función para resaltar las estrellas según la calificación actual
            function resaltarEstrellas(calificacion) {
                estrellas.forEach(function (e, index) {
                    if (index < calificacion) {
                        e.innerHTML = '<i class="fas fa-star" style="font-size: 2em;"></i>';
                    } else {
                        e.innerHTML = '<i class="far fa-star" style="font-size: 2em;"></i>';
                    }
                });
            }

            // Llamar a la función para resaltar las estrellas según la calificación actual
            resaltarEstrellas(calificacionActual);

            // Ocultar el campo de calificación
            inputCalificacion.style.display = 'none';

            estrellas.forEach(function (estrella) {
                estrella.addEventListener('click', function () {
                    const valorEstrella = parseInt(estrella.dataset.valor);

                    // Actualizar el campo oculto con la nueva calificación
                    inputCalificacion.value = valorEstrella;

                    // Resaltar las estrellas seleccionadas
                    resaltarEstrellas(valorEstrella);
                });
            });
        });
    </script>
{% endblock contenido %}

RentaPropiedades/Propiedades/templates/propiedades_arrendador.html
{% extends 'base.html' %}
{% load static %}


{% block nav-Mis_propiedades %}
active
{% endblock nav-Mis_propiedades %}



  


{% block contenido %}

{% if mensaje %}

{{mensaje}}

{% endif %}
<form action="" method="post" id="form">
  {% csrf_token %}
  <div class="text-center container-fluid">
      <h1>Mis propiedades</h1>
  </div>

  {% for propiedad in propiedades %}
    <div class="d-flex justify-content-center align-items-center container-fluid">
      <div class="card mb-3" style="border: 2px solid gray;max-width: 540px; margin: 5px;">
        <div class="row g-0">
          <div class="col-md-4" style="text-align: center;">
            <img src="{{propiedad.primerImagen}}"  style="object-fit: cover; margin: 2px;" class=" card-img-top " width="150" height="150"  alt="...">
            <!-- <img src="" class="card-img-top" style="object-fit: cover;margin: 5px;"> -->
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title">{{propiedad.ubicacion}}</h5>
              <p class="card-text" id="tipo_prop">{{propiedad.get_tipo_display}}</p>
            </div>
          </div>
        </div>
    </div>
      <div>
        <a href="{% url 'detalle_propiedad' propiedad.id %}" class="btn_redondo btn btn-primary" id="btn_detalles">Detalles</a>
        <a href="{% url 'editar_propiedad' propiedad.id %}" style="border-radius: 10px; margin: 10px;" class="btn btn-success" id="id_editar">
          <i class="fas fa-pencil-alt" style="font-size: 2em;"></i> 
        </a>
        <a href="{% url 'confirmacion_eliminacion_propiedad' propiedad.id %}" style="border-radius: 10px; margin: 10px;" class="btn btn-danger" >
          <i class="fas fa-trash" style="font-size: 2em;"></i> 
        </a>
      </div>
    </div>
    
  {% endfor %}

  
</form>
  
<div class="text-center container-fluid">
  <a class="btn btn-info" href="{% url 'agregar_propiedad' %}"> Nueva Propiedad</a>  
</div>

{% endblock contenido %}
    