RentaPropiedades/RentaPropiedades/urls.py
from django.contrib import admin
from Propiedades.views import Bienvenida
from perfiles.views import CustomLoginView
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Propiedades/', include('Propiedades.urls')),
    path('', CustomLoginView.as_view(), name="login"),
    path('home/', Bienvenida.as_view(), name="bienvenida"),
    path('perfiles/', include('perfiles.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

RentaPropiedades/perfiles/urls.py
from django.contrib.auth.views import LogoutView
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

urlpatterns = [
    path('logout/', LogoutView.as_view(),
         name='logout'),
    path('nuevo_estudiante/',
         views.RegistrarEstudiante,
         name='nuevo_estudiante'),
    path('nuevo_arrendador/',
         views.RegistrarArrendador,
         name='nuevo_arrendador'),
    path('compromiso/',
         views.compromiso,
         name='compromiso'),
    path('registrar_contrasena/',
         views.registrar_contrasena,
         name='contrasena'),
    path('confirmacion_cuenta/',
         views.confirmar_cuenta,
         name='confirmar'),
    path('perfil_estudiante/',
         views.verPerfilEstudiante,
         name='perfil_estudiante'),
    path('perfil_arrendador/',
         views.verPerfilArrendador,
         name='perfil_arrendador'),
    path('editar_perfil_estudiante/',
         views.editar_perfil_estudiante,
         name='editar_perfil_estudiante'),
    path('editar_perfil_arrendador/',
         views.editar_perfil_arrendador,
         name='editar_perfil_arrendador'),
    path('eliminar_estudiante/',
         views.eliminarEstudiante,
         name='eliminar_estudiante'),
    path('eliminar_arrendador/',
         views.eliminarArrendador,
         name='eliminar_arrendador'),
    path('confirmar_eliminacion_arrendador/',
         views.confirmaEliminacionArrendador,
         name='confirmar_eliminacion_arrendador'),
    path('confirmar_eliminacion_estudiante/',
         views.confirmaEliminacionEstudiante,
         name='confirmar_eliminacion_estudiante'),
]

if settings.DEBUG:  # pragma no cover
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

RentaPropiedades/perfiles/models.py
from django.db import models
from django.contrib.auth.models import User


class Estudiante (models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=30)
    apellidos = models.CharField(max_length=50)
    edad = models.IntegerField()
    sexo = models.CharField(max_length=1, choices=[(
        'M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')])
    foto_perfil = models.ImageField(
        'Foto', upload_to='perfiles', null=True, blank=True)
    universidad_actual = models.CharField(max_length=100)
    telefono = models.CharField(max_length=10)
    whatsapp = models.CharField(max_length=10)
    correo = models.CharField(max_length=100)
    preferencias_busqueda = models.CharField(max_length=500)
    pasatiempos = models.CharField(max_length=500)
    usuario = models.OneToOneField(
        User, verbose_name="Usuario", on_delete=models.CASCADE)


class Arrendador (models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=30)
    apellidos = models.CharField(max_length=50)
    edad = models.IntegerField()
    sexo = models.CharField(max_length=1, choices=[(
        'M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')])
    foto_perfil = models.ImageField(
        'perfil', upload_to='perfiles', null=True, blank=True)
    ocupacion = models.CharField(max_length=100)
    telefono = models.CharField(max_length=10)
    whatsapp = models.CharField(max_length=10)
    correo = models.CharField(max_length=100)
    preferencias_arrendatarios = models.CharField(max_length=500)
    usuario = models.OneToOneField(
        User, verbose_name="Usuario", on_delete=models.CASCADE)

RentaPropiedades/perfiles/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth.views import LoginView
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages
from django.contrib.auth.models import User, Group
from django.contrib.auth import get_user_model
from .forms import FormEstudiante, FormArrendador, UserForm
from Propiedades.models import Favorito
from Propiedades.models import Propiedad, ImagenPropiedad
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test


def tiene_permiso_estudiante(user):
    return user.groups.filter(name='estudiante').exists()


def tiene_permiso_arrendador(user):
    return user.groups.filter(name='arrendador').exists()


@login_required
@user_passes_test(tiene_permiso_estudiante)
def editar_perfil_estudiante(request):
    usuario = request.user
    estudiante = usuario.estudiante

    if request.method == 'POST':
        form = FormEstudiante(request.POST, request.FILES, instance=estudiante)
        if form.is_valid():
            form.save()
            return redirect('perfil_estudiante')
    else:  # pragma no cover
        imagen_perfil_url = ""
        if estudiante.foto_perfil is not None:
            imagen_perfil_url = estudiante.foto_perfil.url
        form = FormEstudiante(instance=estudiante, initial={
                              'foto_perfil': imagen_perfil_url})
    context = {'form': form, 'user_id': id}
    return render(request, 'editar_perfil_estudiante.html', context)


@login_required
@user_passes_test(tiene_permiso_arrendador)
def editar_perfil_arrendador(request):
    usuario = request.user
    arrendador = usuario.arrendador

    if request.method == 'POST':
        form = FormArrendador(request.POST, request.FILES, instance=arrendador)
        if form.is_valid():
            form.save()
            return redirect('perfil_arrendador')
    else:  # pragma no cover
        imagen_perfil_url = ""
        if arrendador.foto_perfil is not None:
            imagen_perfil_url = arrendador.foto_perfil.url
        form = FormArrendador(instance=arrendador, initial={
                              'foto_perfil': imagen_perfil_url})
    context = {'form': form, 'user_id': id}
    return render(request, 'editar_perfil_arrendador.html', context)


class CustomLoginView(LoginView):
    template_name = 'login.html'
    form_class = AuthenticationForm

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            user = form.get_user()
            if user.check_password(form.cleaned_data['password']):
                # Si los datos son correctos, inicia sesión
                response = self.form_valid(form)
                # Guarda el ID del usuario en la sesión
                self.request.session['user_id'] = user.id
                return response
        else:
            username = form.cleaned_data.get('username')
            # password = form.cleaned_data.get('password')
            User = get_user_model()

            try:
                user = User.objects.get(username=username)
                if not user.has_usable_password():
                    # Si el usuario no tiene una contraseña, elimínalo
                    user.delete()
                    messages.warning(
                        request,
                        'Aún no te has registrado. Inicia tu registro :).')
                    return self.form_invalid(form)
                else:
                    messages.warning(request, 'Contraseña incorrecta :(')
                    return self.form_invalid(form)
            except User.DoesNotExist:
                messages.warning(
                    request,
                    'Aún no te has registrado. Inicia tu registro :).')
                return self.form_invalid(form)


def compromiso(request):
    return render(request, 'compromiso.html')


def confirmar_cuenta(request):
    return render(request, 'confirmacion_cuenta.html')


def RegistrarEstudiante(request):
    if request.method == 'POST':
        form = FormEstudiante(request.POST, request.FILES)
        if form.is_valid():
            estudiante = form.save(commit=False)
            correo = request.POST.get('correo')
            existing_user = User.objects.filter(username=correo).first()
            if existing_user:
                if existing_user.has_usable_password():
                    form.add_error(
                        'correo',
                        'Ya existe un usuario con ese correo electrónico.')
                    template = 'registrar_estudiante.html'
                    return render(request, template, {'form': form})
                else:
                    # El usuario existe pero no tiene una contraseña
                    # lo eliminamos
                    existing_user.delete()

            user = User.objects.create_user(username=correo, email=correo)

            # Verifica si se proporcionó un archivo de imagen
            if not request.FILES.get('foto_perfil'):
                # Si no se proporcionó una imagen
                # establece la imagen predeterminada
                imagen_predeterminada = 'perfiles/1144760.png'
                # Establece la ruta de la imagen predeterminada
                estudiante.foto_perfil.name = imagen_predeterminada

            estudiante.usuario = user
            request.session['correo'] = correo
            request.session.save()
            grupo = Group.objects.get(name='estudiante')
            user.groups.add(grupo)
            estudiante.save()
            return HttpResponseRedirect(reverse('compromiso'))
        else:
            return render(request, 'registrar_estudiante.html', {'form': form})
    else:
        form = FormEstudiante()
        context = {'form': form}
        return render(request, 'registrar_estudiante.html', context)


def RegistrarArrendador(request):
    if request.method == 'POST':
        form = FormArrendador(request.POST, request.FILES)
        if form.is_valid():
            arrendador = form.save(commit=False)
            correo = request.POST.get('correo')
            existing_user = User.objects.filter(username=correo).first()
            if existing_user:
                if existing_user.has_usable_password():
                    # El usuario ya existe y tiene una contraseña válida
                    # muestra un error
                    form.add_error(
                        'correo',
                        'Ya existe un usuario con ese correo electrónico.')
                    template = 'registrar_arrendador.html'
                    return render(request, template, {'form': form})
                else:
                    # El usuario existe pero no tiene una contraseña
                    # lo eliminamos
                    existing_user.delete()

            user = User.objects.create_user(username=correo, email=correo)

            # Verifica si se proporcionó un archivo de imagen
            if not request.FILES.get('foto_perfil'):
                # Si no se proporcionó una imagen
                # establece la imagen predeterminada
                imagen_predeterminada = 'perfiles/1144760.png'
                # Establece la ruta de la imagen predeterminada
                arrendador.foto_perfil.name = imagen_predeterminada

            arrendador.usuario = user
            request.session['correo'] = correo
            request.session.save()
            grupo = Group.objects.get(name='arrendador')
            user.groups.add(grupo)
            arrendador.save()
            return HttpResponseRedirect(reverse('compromiso'))
        else:
            return render(request, 'registrar_arrendador.html', {'form': form})
    else:
        form = FormArrendador()
        context = {'form': form}
        return render(request, 'registrar_arrendador.html', context)


def registrar_contrasena(request):
    id = request.user.id
    if request.method == 'POST':
        form = UserForm(request.POST, request.FILES)
        if form.is_valid():
            # Obtenemos el usuario que acabamos de crear
            # en RegistrarEstudiante desde la sesión
            correo = request.session.get('correo')
            user = User.objects.get(username=correo)

            # Establecemos la contraseña del usuario
            password = request.POST.get('password')
            user.set_password(password)

            user.is_active = True
            # Ahora guardamos con el usuario y la foto de perfil actualizados
            user.save()

            return render(request, 'confirmacion_cuenta.html', {'user': user})
        else:
            # Si el formulario no es válido
            # muestra los errores en la página del formulario
            return render(request, 'registrar_contrasena.html', {'form': form})

    else:
        form = UserForm()

    context = {
        'form': form,
        'userid': id
    }

    return render(request, 'registrar_contrasena.html', context)


@login_required
@user_passes_test(tiene_permiso_estudiante)
def verPerfilEstudiante(request):
    usuario = request.user
    estudiante = usuario.estudiante
    context = {'estudiante': estudiante, 'user': usuario}
    return render(request, 'perfil_estudiante.html', context)


@login_required
@user_passes_test(tiene_permiso_arrendador)
def verPerfilArrendador(request):
    usuario = request.user
    arrendador = usuario.arrendador
    context = {'arrendador': arrendador, 'user': usuario}
    return render(request, 'perfil_arrendador.html', context)


@login_required
@user_passes_test(tiene_permiso_estudiante)
def eliminarEstudiante(request):
    return render(request, 'confirmar_eliminacion_estudiante.html')


@login_required
@user_passes_test(tiene_permiso_arrendador)
def eliminarArrendador(request):
    return render(request, 'confirmar_eliminacion_arrendador.html')

RentaPropiedades/perfiles/templates/confirmar_eliminacion_arrendador.html
{% extends 'base.html' %}

{% load static %}

{% block nav-Ver_Perfil_Estudiante %}
active
{% endblock nav-Ver_Perfil_Estudiante %}

{% block contenido %}
<h1> ¿Estás seguro de eliminar tu perfil?</h1>
  <br>
  <br>

  <h4> Al realizar esta acción, se eliminará de manera definitiva tu perfil del sitio, esto incluye todas las propiedades e imagenes que cargaste. Esta información ya no estará disponible para el resto de usuarios del sitio.
  </h4>


  <span>
    <a href="{% url 'bienvenida' %}" class="btn btn-warning">Cancelar</a>
    <a href="{% url 'confirmar_eliminacion_arrendador' %}" class="btn btn-danger"> Eliminar Perfil</a>
</span>
{% endblock contenido %}

RentaPropiedades/perfiles/templates/confirmar_eliminacion_estudiante.html
{% extends 'base.html' %}

{% load static %}

{% block nav-Ver_Perfil_Estudiante %}
active
{% endblock nav-Ver_Perfil_Estudiante %}

{% block contenido %}
<h1> ¿Estás seguro de eliminar tu perfil?</h1>
  <br>
  <br>

  <h4> Al realizar esta acción, se eliminará de manera definitiva tu perfil del sitio y los datos guardados dentro de él serán descartados de forma automática.</h4>


  <span>
    <a id="id_cancelar" href="{% url 'bienvenida' %}" class="btn btn-warning">Cancelar</a>
    <a id="id_eliminar" href="{% url 'confirmar_eliminacion_estudiante' %}" class="btn btn-danger"> Eliminar Perfil</a>
  </span>
{% endblock contenido %}
    

RentaPropiedades/perfiles/templates/perfil_arrendador.html
{% extends 'base.html' %}

{% load static %}

{% block nav-Ver_Perfil_Arrendador %}
active
{% endblock nav-Ver_Perfil_Arrendador %}

{% block contenido %}



<div class="formulario-container">

  <div class="card card-user">
    <div class="card-image">
        <img src="https://ununsplash.imgix.net/photo-1431578500526-4d9613015464?fit=crop&fm=jpg&h=300&q=75&w=400" alt="...">
    </div>
    <div class="card-body">
      <div class="author">
        <a>
          <img class="avatar border-gray" src="{{ arrendador.foto_perfil.url }}" alt="...">
          <h5 class="title" style="color: purple;">{{ arrendador.nombre }} {{ arrendador.apellidos }}</h5>
        </a>
        <p class="description"><strong>Arrendador</strong></p>
        <p class="description"><strong>Edad: </strong>{{ arrendador.edad }}</p>
        <p class="description"><strong>Sexo: </strong>{{ arrendador.get_sexo_display }}</p>
        <p class="description"><strong>Ocupación: </strong>{{ arrendador.ocupacion }}</p>
        <p class="description"><strong>Teléfono: </strong>{{ arrendador.telefono }}</p>
        <p class="description"><strong>Preferencias de perfil de arrendatario: </strong>{{ arrendador.preferencias_arrendatarios }}</p>
      </div>
    </div>
    <hr>
    <div class="button-container mr-auto ml-auto">
      <div class="button-container mr-auto ml-auto">
        <button class="btn btn-simple btn-link btn-icon">
          <a href="tel: {{arrendador.telefono}}"><i class="fa fa-phone" style="width: 35px; font-size: 35px;"></i></a>
        </button>
        <button class="btn btn-simple btn-link btn-icon">
          <a href="https://api.whatsapp.com/send?phone=52{{ arrendador.whatsapp }}"><i class="fab fa-whatsapp"></i></a>
        </button>
        <button class="btn btn-simple btn-link btn-icon">
          <a href="mailto: {{arrendador.correo}}"><i class="fa fa-envelope"></i></a>
        </button>
      </div>
    </div>
    <div class="button-container mr-auto ml-auto">
      <form method="post">
        <span>
          <a href="{% url 'editar_perfil_arrendador' %}" class="btn btn-info">Editar Perfil</a>
        </span>
      </form>
    </div>
  </div>

  
  
</div>

{% endblock contenido  %}

<!-- <div class="info-container">
  <div class="info">
    <p><strong>Nombre: </strong>{{ arrendador.nombre }} {{ arrendador.apellidos }}</p>
    <p><strong>Edad: </strong>{{ arrendador.edad }}</p>
    <p><strong>Sexo: </strong>{{ arrendador.get_sexo_display }}</p>
    <p><strong>Ocupación: </strong>{{ arrendador.ocupacion }}</p>
    <p><strong>Teléfono: </strong>{{ arrendador.telefono }}</p>
    <p><strong>WhatsApp: </strong>{{ arrendador.whatsapp }}</p>
    <p><strong>Correo Electrónico: </strong>{{ arrendador.correo }}</p>
    <p><strong>Preferencias de perfil de arrendatario: </strong>{{ arrendador.preferencias_arrendatarios }}</p>
    <form method="post">
      <span>
        <a href="{% url 'bienvenida' %}" class="btn btn-warning"> Volver</a>
        <a href="{% url 'editar_perfil_arrendador' %}" class="btn btn-info">Editar Perfil</a>
      </span>
    </form>
    
  </div>
  <div class="imagen-container">
    <img class="foto-perfil" src="{{ arrendador.foto_perfil.url }}" alt="Foto de Perfil">
  </div>
</div> -->

RentaPropiedades/perfiles/templates/perfil_estudiante.html
{% extends 'base.html' %}

{% load static %}

{% block nav-Ver_Perfil_Estudiante %}
active
{% endblock nav-Ver_Perfil_Estudiante %}

{% block contenido %}



<div class="formulario-container">

  <div class="card card-user">
    <div class="card-image">
        <img src="https://ununsplash.imgix.net/photo-1431578500526-4d9613015464?fit=crop&fm=jpg&h=300&q=75&w=400" alt="...">
    </div>
    <div class="card-body">
      <div class="author">
        <a>
          <img class="avatar border-gray" src="{{ estudiante.foto_perfil.url }}" alt="...">
          <h5 class="title" style="color: purple;">{{ estudiante.nombre }} {{ estudiante.apellidos }}</h5>
        </a>
        <p class="description"><strong>Estudiante</strong></p>
        <p class="description"><strong>Edad: </strong>{{ estudiante.edad }}</p>
        <p class="description"><strong>Sexo: </strong>{{ estudiante.get_sexo_display }}</p>
        <p class="description"><strong>Universidad Actual: </strong>{{ estudiante.universidad_actual }}</p>
        <p class="description"><strong>Teléfono: </strong>{{ estudiante.telefono }}</p>
        <p class="description"><strong>Preferencias de búsqueda: </strong>{{ estudiante.preferencias_busqueda }}</p>
        <p class="description"><strong>Pasatiempos: </strong>{{ estudiante.pasatiempos }}</p>
      </div>
    </div>
    <hr>
    <div class="button-container mr-auto ml-auto">
      <div class="button-container mr-auto ml-auto">
        <button class="btn btn-simple btn-link btn-icon">
          <a id="id_telefono" href="tel: {{estudiante.telefono}}"><i class="fa fa-phone" style="width: 35px; font-size: 35px;"></i></a>
        </button>
        <button class="btn btn-simple btn-link btn-icon">
          <a id="id_whatsapp" href="https://api.whatsapp.com/send?phone=52{{ estudiante.whatsapp }}"><i class="fab fa-whatsapp"></i></a>
        </button>
        <button class="btn btn-simple btn-link btn-icon">
          <a id="id_correo" href="mailto: {{estudiante.correo}}"><i class="fa fa-envelope"></i></a>
        </button>
      </div>
    </div>
    <div class="button-container mr-auto ml-auto">
      <form method="post">
        <span>
          <a id="btn-editar" href="{% url 'editar_perfil_estudiante' %}" class="btn btn-info">Editar Perfil</a>
        </span>
      </form>
    </div>
  </div>

</div>

{% endblock contenido  %}

RentaPropiedades/perfiles/templates/registrar_arrendador.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />

  
  <link rel="icon" type="image/png" href="{% static 'img/favicon.ico' %}">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  
  
  <title> Sistema de consultas de propiedades en renta en Zacatecas y Guadalupe </title>
  <!--     Fonts and icons     -->
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
  <!-- CSS Files -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">
  <link href="{% static 'css/light-bootstrap-dashboard.css' %}" rel="stylesheet" />

  <style>
      
      /*id que Django genera automáticamente para el campo ‘sexo’ en nuestro formulario, y 
      aplicará las propiedades de flexbox para mostrar los botones de radio en línea.*/
      #id_sexo {
        display: inline-flex;
        align-items: center; /* Alinea verticalmente los radio buttons con los demás elementos */
      }
    
      #id_sexo label {
          margin-right: 25px; /* Ajusta el margen entre los botones de los radio buttons */
          margin-left: 0; /* Alinea los radio buttons a la izquierda, 0 para que no se mueva */
      }
  </style>
</head>

<body>
  <div class="container container-fluid">
    <div class="jumbotron mt-5 text-center" style="background-color: #e1e1e1;">
      <h1 class="text-center"><strong>Crear Perfil Arrendador</strong></h1>
    </div>
    

    <div class="container_form">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}

        
        <div class="row container text-center ">
          <div class="col-md-6">
            <a class="btn btn btn-danger" href="{% url 'login' %}" role="button">Cancelar</a>
          </div>
          <div class="col-md-6">
            <button type="submit" class="btn_siguiente btn_redondo btn btn-primary">Siguiente</button>
          </div>

        </div>
      </form>
    </div>

</body>

<script src="{% static 'js/core/jquery.3.2.1.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/core/popper.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/core/bootstrap.min.js' %}" type="text/javascript"></script>
<!--  Plugin for Switches, full documentation here: http://www.jque.re/plugins/version3/bootstrap.switch/ -->
<script src="{% static 'js/plugins/bootstrap-switch.js' %}"></script>
<!--  Google Maps Plugin    -->
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
<!--  Chartist Plugin  -->
<script src="{% static 'js/plugins/chartist.min.js' %}"></script>
<!--  Notifications Plugin    -->
<script src="{% static 'js/plugins/bootstrap-notify.js' %}"></script>
<!-- Control Center for Light Bootstrap Dashboard: scripts for the example pages etc -->
<script src="{% static 'js/light-bootstrap-dashboard.js' %}" type="text/javascript"></script>
</html>

RentaPropiedades/perfiles/templates/registrar_estudiante.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />

  
  <link rel="icon" type="image/png" href="{% static 'img/favicon.ico' %}">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  
  
  <title> Sistema de consultas de propiedades en renta en Zacatecas y Guadalupe </title>
  <!--     Fonts and icons     -->
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
  <!-- CSS Files -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">
  <link href="{% static 'css/light-bootstrap-dashboard.css' %}" rel="stylesheet" />

  <style>
      
      /*id que Django genera automáticamente para el campo ‘sexo’ en nuestro formulario, y 
      aplicará las propiedades de flexbox para mostrar los botones de radio en línea.*/
      #id_sexo {
        display: inline-flex;
        align-items: center; /* Alinea verticalmente los radio buttons con los demás elementos */
      }
    
      #id_sexo label {
          margin-right: 25px; /* Ajusta el margen entre los botones de los radio buttons */
          margin-left: 0; /* Alinea los radio buttons a la izquierda, 0 para que no se mueva */
      }
  </style>
</head>

<body>
  <div class="container container-fluid">
    <div class="jumbotron mt-5 text-center" style="background-color: #e1e1e1;">
      <h1 class="text-center"><strong>Crear Perfil Estudiante</strong></h1>
    </div>
    

    <div class="container_form">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}

        
        <div class="row container text-center ">
          <div class="col-md-6">
            <a class="btn btn btn-danger" href="{% url 'login' %}" role="button">Cancelar</a>
          </div>
          <div class="col-md-6">
            <button type="submit" class="btn_siguiente btn_redondo btn btn-primary">Siguiente</button>
          </div>

        </div>
      </form>
    </div>

</body>

<script src="{% static 'js/core/jquery.3.2.1.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/core/popper.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/core/bootstrap.min.js' %}" type="text/javascript"></script>
<!--  Plugin for Switches, full documentation here: http://www.jque.re/plugins/version3/bootstrap.switch/ -->
<script src="{% static 'js/plugins/bootstrap-switch.js' %}"></script>
<!--  Google Maps Plugin    -->
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
<!--  Chartist Plugin  -->
<script src="{% static 'js/plugins/chartist.min.js' %}"></script>
<!--  Notifications Plugin    -->
<script src="{% static 'js/plugins/bootstrap-notify.js' %}"></script>
<!-- Control Center for Light Bootstrap Dashboard: scripts for the example pages etc -->
<script src="{% static 'js/light-bootstrap-dashboard.js' %}" type="text/javascript"></script>
</html>